# Generated by Django 4.2.20 on 2025-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendLivraria', '0004_livro_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(related_name='livros', to='backendLivraria.categoria'),
        ),
    ]
