# Generated by Django 4.2.20 on 2025-03-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendLivraria', '0005_remove_livro_categoria_livro_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ManyToManyField(related_name='livros', to='backendLivraria.editora'),
        ),
    ]
